// SPDX-License-Identifier: Apache-2.0
//! DeepSeek-V4-Flash MoE block — pure-CPU f32 reference (f64 accumulation).
//!
//! Clean-room port of the transformers-5.8.1 reference modules, bit-exact vs
//! `DeepseekV4TopKRouter`, `DeepseekV4HashRouter`, `DeepseekV4Experts` and the
//! shared `DeepseekV4MLP`, validated by the hermetic test at the bottom against
//! `tests/fixtures/dsv4/moe_block.json` (generated by
//! `scripts/dsv4/dump_moe_fixture.py`, itself cross-checked vs transformers).
//!
//! ## Math (confirmed from modeling_deepseek_v4.py)
//!
//! **Router score:** `sqrtsoftplus(x) = sqrt(softplus(x))`, stable softplus =
//! `log1p(exp(-|x|)) + max(x,0)` (== `config.scoring_func`).
//!
//! **TopK router (noaux_tc):** `logits = hs @ weight^T`; `scores = sqrtsoftplus(logits)`;
//! select `top_k` experts by `argmax(scores + e_score_correction_bias)` (bias used
//! for SELECTION only); gather weights from `scores` (NOT the biased sel); normalize
//! `w / (sum(w) + 1e-20)`; multiply by `routed_scaling_factor`.
//!
//! **Hash router (bootstrap layers):** identical, except the selected expert ids are
//! a frozen `tid2eid[input_id]` lookup (per token, `top_k` ids) instead of argmax.
//!
//! **Routed expert (swiglu + swiglu_limit):** for token `x` and expert `e`:
//! `gu = gate_up[e] @ x` (gate_up[e] is `[2I,H]`), `g = gu[:I]`, `u = gu[I:]`;
//! `g = min(g, limit)`, `u = clamp(u, -limit, limit)`; `h = silu(g) * u`;
//! contribution `= (down[e] @ h) * w` (down[e] is `[H,I]`).
//!
//! **Shared expert (`DeepseekV4MLP`):** `down @ (silu(gate @ x) * (up @ x))`,
//! separate gate/up/down weights, weight 1.0, **NO swiglu_limit clamp**. It uses the
//! same `config.intermediate_size` as the routed experts (both == 2048 in the real
//! config), so a single `i` dimension serves both.
//!
//! **Block combination (`DeepseekV4SparseMoeBlock.forward`):**
//! `out = routed + shared_experts(residual)` where the routed weights ALREADY carry
//! `routed_scaling_factor` (folded in by the router) and the shared expert is added
//! afterward, unscaled. `residual` is the block input `hs`.
//!
//! All matmul/accumulation is done in f64 to mirror the oracle's float64 math, then
//! cast to f32 for the returned activations (matching `src/dsv4.rs`).

/// `sqrtsoftplus(x) = sqrt(softplus(x))` with the numerically-stable softplus
/// `log1p(exp(-|x|)) + max(x, 0)`. Computed in f64.
pub fn sqrtsoftplus(x: f32) -> f32 {
    let x = x as f64;
    let softplus = (-x.abs()).exp().ln_1p() + x.max(0.0);
    softplus.sqrt() as f32
}

/// `silu(z) = z * sigmoid(z)`, f64.
#[inline]
fn silu_f64(z: f64) -> f64 {
    z * (1.0 / (1.0 + (-z).exp()))
}

/// Row-major `[rows, cols]` matrix times a length-`cols` vector, f64 accumulate.
/// `w[r,c] = mat[r*cols + c]`; returns `mat @ x` of length `rows`.
fn matvec(mat: &[f32], x: &[f32], rows: usize, cols: usize) -> Vec<f64> {
    let mut out = vec![0.0f64; rows];
    for r in 0..rows {
        let base = r * cols;
        let mut acc = 0.0f64;
        for c in 0..cols {
            acc += mat[base + c] as f64 * x[c] as f64;
        }
        out[r] = acc;
    }
    out
}

/// ★ LEVER B (router rayon): BIT-IDENTICAL parallel twin of `matvec`. Each output
/// row is an independent f64 dot product computed with the SAME inner accumulation
/// order as `matvec`; only the rows are spread across cores, and `collect` preserves
/// index order — so `matvec_par == matvec` element-for-element (argmax-exact by
/// construction). Used for the MoE router gate projection (`[n_experts, h] @ x`),
/// the per-token host-serial cost the decode profile measured as the #1 bucket
/// (66.8 ms/tok over ~40 MoE layers). Mirrors the qwen35 shared-expert rayon win.
fn matvec_par(mat: &[f32], x: &[f32], rows: usize, cols: usize) -> Vec<f64> {
    use rayon::prelude::*;
    (0..rows)
        .into_par_iter()
        .map(|r| {
            let base = r * cols;
            let mut acc = 0.0f64;
            for c in 0..cols {
                acc += mat[base + c] as f64 * x[c] as f64;
            }
            acc
        })
        .collect()
}

/// The router gate matvec, dispatched to `matvec_par` when
/// `VLLM_VULKAN_DSV4_ROUTER_RAYON` is set (default-OFF, gate-then-flip). Bit-identical
/// either way. Env read is cached once (per-token ×40-layer hot path).
fn router_matvec(mat: &[f32], x: &[f32], rows: usize, cols: usize) -> Vec<f64> {
    if router_rayon_enabled() {
        matvec_par(mat, x, rows, cols)
    } else {
        matvec(mat, x, rows, cols)
    }
}

/// `VLLM_VULKAN_DSV4_ROUTER_RAYON` — parallelize the host MoE-router gate matvec
/// across cores (bit-identical). DEFAULT-ON as of the combined A+B on-node confirm
/// (PP-10 @1850: argmax 11111 + gen bit-identical to the host oracle at GEN=8 AND
/// GEN=64, stacked with LEVER A). Set `=0`/`=false` to force the serial path (the
/// parallelization can never change the argmax — the reduction order is identical).
fn router_rayon_enabled() -> bool {
    use std::sync::OnceLock;
    static F: OnceLock<bool> = OnceLock::new();
    *F.get_or_init(|| {
        std::env::var("VLLM_VULKAN_DSV4_ROUTER_RAYON")
            .map(|v| v != "0" && v != "false")
            .unwrap_or(true)
    })
}

/// Gathered scores for a single token's `top_k` selected experts → normalized,
/// scaled weights. `sel_scores[j]` is `scores[idx[j]]` (the UNBIASED score).
fn normalize_weights(sel_scores: &[f64], scaling: f32, norm: bool) -> Vec<f32> {
    if norm {
        let sum: f64 = sel_scores.iter().sum::<f64>() + 1e-20;
        sel_scores
            .iter()
            .map(|&w| (w / sum * scaling as f64) as f32)
            .collect()
    } else {
        sel_scores
            .iter()
            .map(|&w| (w * scaling as f64) as f32)
            .collect()
    }
}

/// TopK router (noaux_tc). `hs` is `[t*h]` row-major, `weight` is `[n_experts*h]`,
/// `corr_bias` is `[n_experts]`. Returns `(idx[t*top_k], w[t*top_k])` where the
/// selected expert ids per token are ordered by descending `scores+bias` (selection
/// order) and the weights are gathered from the unbiased `scores`, normalized, and
/// scaled by `scaling`.
pub fn topk_router(
    hs: &[f32],
    weight: &[f32],
    corr_bias: &[f32],
    t: usize,
    h: usize,
    n_experts: usize,
    top_k: usize,
    scaling: f32,
    norm: bool,
) -> (Vec<usize>, Vec<f32>) {
    let mut idx_out = vec![0usize; t * top_k];
    let mut w_out = vec![0.0f32; t * top_k];
    for ti in 0..t {
        let x = &hs[ti * h..(ti + 1) * h];
        let logits = router_matvec(weight, x, n_experts, h); // [n_experts]
        let scores: Vec<f64> = logits.iter().map(|&l| sqrtsoftplus(l as f32) as f64).collect();
        // selection key = scores + bias; pick top_k descending (stable by expert id on ties).
        let mut order: Vec<usize> = (0..n_experts).collect();
        order.sort_by(|&a, &b| {
            let ka = scores[a] + corr_bias[a] as f64;
            let kb = scores[b] + corr_bias[b] as f64;
            kb.partial_cmp(&ka).unwrap().then(a.cmp(&b))
        });
        let sel = &order[..top_k];
        let sel_scores: Vec<f64> = sel.iter().map(|&e| scores[e]).collect();
        let w = normalize_weights(&sel_scores, scaling, norm);
        for j in 0..top_k {
            idx_out[ti * top_k + j] = sel[j];
            w_out[ti * top_k + j] = w[j];
        }
    }
    (idx_out, w_out)
}

/// Hash router (bootstrap layers 0-2). Expert selection is the frozen
/// `tid2eid[input_id]` lookup; weights are the same `sqrtsoftplus(hs@weight^T)`
/// gathered at those ids, normalized and scaled. `tid2eid` is `[vocab*top_k]`
/// row-major, `input_ids` is `[t]`. Returns `(idx[t*top_k], w[t*top_k])`.
pub fn hash_router(
    hs: &[f32],
    weight: &[f32],
    tid2eid: &[i64],
    input_ids: &[u32],
    t: usize,
    h: usize,
    n_experts: usize,
    top_k: usize,
    scaling: f32,
    norm: bool,
) -> (Vec<usize>, Vec<f32>) {
    let mut idx_out = vec![0usize; t * top_k];
    let mut w_out = vec![0.0f32; t * top_k];
    for ti in 0..t {
        let x = &hs[ti * h..(ti + 1) * h];
        let logits = router_matvec(weight, x, n_experts, h);
        let scores: Vec<f64> = logits.iter().map(|&l| sqrtsoftplus(l as f32) as f64).collect();
        let tid = input_ids[ti] as usize;
        let sel: Vec<usize> = (0..top_k)
            .map(|j| tid2eid[tid * top_k + j] as usize)
            .collect();
        let sel_scores: Vec<f64> = sel.iter().map(|&e| scores[e]).collect();
        let w = normalize_weights(&sel_scores, scaling, norm);
        for j in 0..top_k {
            idx_out[ti * top_k + j] = sel[j];
            w_out[ti * top_k + j] = w[j];
        }
    }
    (idx_out, w_out)
}

/// One routed expert applied to one token, WITH the swiglu_limit clamp.
/// `gate_up` is `[2i*h]` (row-major `[2I,H]`), `down` is `[h*i]` (row-major `[H,I]`).
/// Returns the length-`h` contribution (before multiplying by the router weight).
pub fn swiglu_expert(
    x_row: &[f32],
    gate_up: &[f32],
    down: &[f32],
    h: usize,
    i: usize,
    limit: f32,
) -> Vec<f32> {
    let gu = matvec(gate_up, x_row, 2 * i, h); // [2I]
    let lim = limit as f64;
    let mut hid = vec![0.0f32; i];
    for k in 0..i {
        let g = gu[k].min(lim); // gate: clamp max
        let u = gu[i + k].clamp(-lim, lim); // up: clamp [-lim, lim]
        hid[k] = (silu_f64(g) * u) as f32;
    }
    let out = matvec(down, &hid, h, i); // [H]
    out.iter().map(|&v| v as f32).collect()
}

/// Shared expert (`DeepseekV4MLP`): `down @ (silu(gate @ x) * (up @ x))`.
/// `gate`/`up` are `[i*h]` (row-major `[I,H]`), `down` is `[h*i]` (`[H,I]`).
/// NO swiglu_limit clamp. Returns the length-`h` output.
pub fn mlp_expert(
    x_row: &[f32],
    gate: &[f32],
    up: &[f32],
    down: &[f32],
    h: usize,
    i: usize,
) -> Vec<f32> {
    let g = matvec(gate, x_row, i, h); // [I]
    let u = matvec(up, x_row, i, h); // [I]
    let mut hid = vec![0.0f32; i];
    for k in 0..i {
        hid[k] = (silu_f64(g[k]) * u[k]) as f32;
    }
    let out = matvec(down, &hid, h, i);
    out.iter().map(|&v| v as f32).collect()
}

/// Full MoE block forward: `routed + shared`.
///
/// Given the router output (`router_idx[t*top_k]`, `router_w[t*top_k]` — weights
/// already carrying `routed_scaling_factor`), streams only the hit routed experts
/// via `fetch_expert(e) -> (&gate_up[2i*h], &down[h*i])`, applies the swiglu_limit
/// clamp, accumulates `contribution * weight`, then adds the shared expert output.
///
/// `hs` is `[t*h]` (the block input == residual). Returns `[t*h]`.
///
/// `fetch_expert` returns borrowed slices so the caller can stream/dequantize an
/// expert's weights on demand (e.g. from a memory-mapped or NAS-streamed store).
pub fn moe_forward<'a, F>(
    hs: &[f32],
    t: usize,
    h: usize,
    i: usize,
    router_idx: &[usize],
    router_w: &[f32],
    top_k: usize,
    limit: f32,
    mut fetch_expert: F,
    shared_gate: &[f32],
    shared_up: &[f32],
    shared_down: &[f32],
) -> Vec<f32>
where
    F: FnMut(usize) -> (&'a [f32], &'a [f32]),
{
    let mut out = vec![0.0f32; t * h];
    for ti in 0..t {
        let x = &hs[ti * h..(ti + 1) * h];
        let base = ti * h;
        // routed experts
        for j in 0..top_k {
            let e = router_idx[ti * top_k + j];
            let w = router_w[ti * top_k + j];
            let (gate_up, down) = fetch_expert(e);
            let contrib = swiglu_expert(x, gate_up, down, h, i, limit);
            for c in 0..h {
                out[base + c] += contrib[c] * w;
            }
        }
        // shared expert (weight 1.0, no limit)
        let sh = mlp_expert(x, shared_gate, shared_up, shared_down, h, i);
        for c in 0..h {
            out[base + c] += sh[c];
        }
    }
    out
}

#[cfg(test)]
mod moe_tests {
    use super::*;
    use serde_json::Value;
    use std::collections::HashSet;

    fn f32v(v: &Value) -> Vec<f32> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_f64().unwrap() as f32)
            .collect()
    }
    fn usizev(v: &Value) -> Vec<usize> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_u64().unwrap() as usize)
            .collect()
    }

    #[test]
    fn moe_block_matches_reference() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/dsv4/moe_block.json");
        let raw = std::fs::read_to_string(path)
            .expect("moe_block.json fixture (run scripts/dsv4/dump_moe_fixture.py --dump)");
        let j: Value = serde_json::from_str(&raw).unwrap();

        let t = j["T"].as_u64().unwrap() as usize;
        let h = j["H"].as_u64().unwrap() as usize;
        let e_n = j["E"].as_u64().unwrap() as usize;
        let i = j["I"].as_u64().unwrap() as usize;
        let top_k = j["top_k"].as_u64().unwrap() as usize;
        let limit = j["limit"].as_f64().unwrap() as f32;
        let scaling = j["scaling"].as_f64().unwrap() as f32;

        let hs = f32v(&j["hs"]);
        let input_ids: Vec<u32> = j["input_ids"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_u64().unwrap() as u32)
            .collect();
        let gate_weight = f32v(&j["gate_weight"]);
        let corr_bias = f32v(&j["corr_bias"]);
        let tid2eid: Vec<i64> = j["tid2eid"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_i64().unwrap())
            .collect();
        let gate_up = f32v(&j["gate_up"]); // [E,2I,H]
        let down = f32v(&j["down"]); // [E,H,I]
        let shared_gate = f32v(&j["shared_gate"]);
        let shared_up = f32v(&j["shared_up"]);
        let shared_down = f32v(&j["shared_down"]);

        let ref_idx_topk = usizev(&j["idx_topk"]);
        let ref_w_topk = f32v(&j["w_topk"]);
        let ref_idx_hash = usizev(&j["idx_hash"]);
        let ref_moe_out = f32v(&j["moe_out"]);

        // ---- topk router: idx set-match per token + weight max_abs_err ----
        let (idx_tk, w_tk) =
            topk_router(&hs, &gate_weight, &corr_bias, t, h, e_n, top_k, scaling, true);
        let mut w_err = 0.0f32;
        for ti in 0..t {
            let mine: HashSet<usize> =
                idx_tk[ti * top_k..(ti + 1) * top_k].iter().copied().collect();
            let refs: HashSet<usize> =
                ref_idx_topk[ti * top_k..(ti + 1) * top_k].iter().copied().collect();
            assert_eq!(mine, refs, "topk idx set mismatch at token {ti}");
            // align weights by expert id
            for j in 0..top_k {
                let e = idx_tk[ti * top_k + j];
                let wm = w_tk[ti * top_k + j];
                // find same e in reference
                let pos = (0..top_k)
                    .find(|&k| ref_idx_topk[ti * top_k + k] == e)
                    .unwrap();
                let wr = ref_w_topk[ti * top_k + pos];
                w_err = w_err.max((wm - wr).abs());
            }
        }
        assert!(w_err < 1e-4, "topk weight max_abs_err {w_err} >= 1e-4");

        // ---- hash router: idx exact ----
        let (idx_hs, _w_hs) = hash_router(
            &hs, &gate_weight, &tid2eid, &input_ids, t, h, e_n, top_k, scaling, true,
        );
        assert_eq!(idx_hs, ref_idx_hash, "hash router idx mismatch");

        // ---- full moe_forward (using our topk router output) vs reference ----
        let fetch = |e: usize| -> (&[f32], &[f32]) {
            let gu = &gate_up[e * 2 * i * h..(e + 1) * 2 * i * h];
            let dn = &down[e * h * i..(e + 1) * h * i];
            (gu, dn)
        };
        let moe = moe_forward(
            &hs, t, h, i, &idx_tk, &w_tk, top_k, limit, fetch, &shared_gate, &shared_up,
            &shared_down,
        );
        let mut moe_err = 0.0f32;
        for k in 0..t * h {
            moe_err = moe_err.max((moe[k] - ref_moe_out[k]).abs());
        }
        assert!(moe_err < 1e-3, "moe_forward max_abs_err {moe_err} >= 1e-3");

        println!(
            "dsv4_moe: topk w_err={w_err:.3e}  hash idx exact  moe_forward max_abs_err={moe_err:.3e}"
        );
    }
}
