// SPDX-License-Identifier: Apache-2.0
//! Vulkan compute pipeline cache.
//!
//! A `PipelineCache` holds one `VkPipeline` per SPIR-V shader variant.
//! All pipelines share a single `VkDescriptorSetLayout` with 12 storage
//! buffer bindings (matching the llama.cpp convention).

use ash::vk;
use std::collections::HashMap;

/// Maximum number of storage buffer bindings per pipeline.
pub const MAX_BINDINGS: u32 = 12;

/// How a shader is compiled in `PipelineCache::new`, decided purely by name.
/// This is the single Rust-side home for the enum; the *rule* that maps a
/// shader name to a class lives in `build.rs::class_of` (mirrored exactly)
/// and is baked into the generated `SHADER_REGISTRY`.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum ShaderClass {
    Plain,
    Matvec,
    MatvecSubgroup,
    MulMm,
    Flash,
    RmsNorm,
}

/// A compiled `VkPipeline` together with its layout and workgroup parameters.
pub struct Pipeline {
    pub name: String,
    pub module: vk::ShaderModule,
    pub layout: vk::PipelineLayout,
    pub pipeline: vk::Pipeline,
    /// Number of storage buffer bindings this shader uses.
    pub binding_count: u32,
}

/// One allocation of push-constant data (up to 128 bytes).
pub type PushConstants = Vec<u8>;

/// Manages a set of compute pipelines for one logical device.
pub struct PipelineCache {
    device: ash::Device,
    subgroup_size: u32,
    pub descriptor_set_layout: vk::DescriptorSetLayout,
    pipelines: HashMap<String, Pipeline>,
}

impl PipelineCache {
    /// Create a new pipeline cache for the given device.
    ///
    /// `shader_spvs`: map from shader name → SPIR-V bytes.
    pub fn new(
        device: ash::Device,
        caps: crate::device::DeviceCaps,
        shader_spvs: &HashMap<&str, &[u8]>,
    ) -> Result<Self, String> {
        // One global descriptor set layout with MAX_BINDINGS storage buffers.
        let bindings: Vec<vk::DescriptorSetLayoutBinding> = (0..MAX_BINDINGS)
            .map(|i| {
                vk::DescriptorSetLayoutBinding::default()
                    .binding(i)
                    .descriptor_type(vk::DescriptorType::STORAGE_BUFFER)
                    .descriptor_count(1)
                    .stage_flags(vk::ShaderStageFlags::COMPUTE)
            })
            .collect();

        let dsl_ci = vk::DescriptorSetLayoutCreateInfo::default()
            .bindings(&bindings);
        let dsl = unsafe { device.create_descriptor_set_layout(&dsl_ci, None) }
            .map_err(|e| format!("create_descriptor_set_layout: {e}"))?;

        let mut cache = PipelineCache {
            device: device.clone(),
            subgroup_size: caps.subgroup_size,
            descriptor_set_layout: dsl,
            pipelines: HashMap::new(),
        };

        // Compile all provided shaders. Which compile_* fn each shader routes
        // through is decided purely by name; that rule is now the single
        // `shader_registry::SHADER_REGISTRY` table (generated by build.rs's
        // `class_of`, mirroring the comments below verbatim) rather than a
        // hand-duplicated if/else chain here.
        let class: HashMap<&str, ShaderClass> = crate::shader_registry::SHADER_REGISTRY
            .iter()
            .map(|(n, c, _)| (*n, *c))
            .collect();

        let mut failed: Vec<String> = Vec::new();
        for (&name, &spv) in shader_spvs {
            // (Upstream still hand-rolls MATVEC_SHADERS/MATMUL_SHADERS string
            // arrays here and explicitly drops the dead/dangerous
            // `mul_mat_vec_f32_f32_f32_subgroup`; the fork's SHADER_REGISTRY
            // table below supersedes that routing and never registers it.)
            // M10: genuinely-wave64 shader — a 64-thread workgroup IS one subgroup
            // (baked in GLSL, no spec constant fixes it). Skip on non-64 devices
            // rather than compile a wrong kernel.
            if (name == "paged_attn_decode_f32_sg" || name == "paged_attn_decode_f16_sg"
                || name == "laguna_gpu_sdpa")
                && cache.subgroup_size != 64 {
                log::warn!(
                    "skipping '{name}': requires subgroup_size==64, device has {}",
                    cache.subgroup_size
                );
                continue;
            }
            let result = match class.get(name).copied().unwrap_or(ShaderClass::Plain) {
                // RMSNorm shaders need do_multiply specialization variants.
                ShaderClass::RmsNorm => cache.compile_rms_norm(name, spv),
                // H4: no-shmem subgroupAdd reduction (USE_SUBGROUP_ADD_NO_SHMEM) is
                // correct ONLY when the workgroup is a single subgroup. Compile with
                // BLOCK_SIZE = device subgroup_size, and NO _r* siblings.
                ShaderClass::MatvecSubgroup => cache.compile_matvec_subgroup(name, spv),
                // Shaders using layout(local_size_x_id=0) need BLOCK_SIZE
                // specialization + _rN siblings. The three bases swept by the
                // kernel-geometry lever additionally get their `_bs{bs}_r{r}`
                // siblings (winners from the on-node debug_*_geometry sweep;
                // see push_constants::geom_pick).
                ShaderClass::Matvec => cache.compile_matvec(name, spv).and_then(|_| {
                    let combos = crate::push_constants::geom_combos_for(name);
                    if combos.is_empty() { Ok(()) } else {
                        cache.compile_matvec_geom(name, spv, combos)
                    }
                }),
                // Tiled GEMM (mul_mm.comp). The shader's default spec constants
                // (BLOCK_SIZE=64) are INCONSISTENT with the tile geometry: the
                // scalar path partitions the BMxBN tile into (BM/WM)*(BN/WN)
                // logical warps of WARP threads, so it needs BLOCK_SIZE =
                // (BM/WM)*(BN/WN)*WARP = 2*2*32 = 128 threads. With the default
                // 64 only half the warps exist, half the warp tiles are never
                // computed, and (combined with the wrong default) the output
                // comes back all zero. llama.cpp always sets these explicitly.
                // Phase A quant-batched-GEMM (plan-quant-batched-matmul.md):
                // the DATA_A_Q8_0/DATA_A_MLX4 mul_mm variants need BK=32 (spec
                // constant 3), which compile_mul_mm never sets (correctly, for
                // the f32/f16 shaders that #define BK directly and never
                // declare that constant_id) — route by name to the dedicated
                // quant compiler instead.
                ShaderClass::MulMm if name.starts_with("matmul_q8_0_")
                    || name.starts_with("matmul_mlx4_") => cache.compile_mul_mm_quant(name, spv),
                ShaderClass::MulMm => cache.compile_mul_mm(name, spv),
                // Flash attention (flash_attn.comp). Its default spec constants
                // (SubGroupSize=32, D_split=16, Br=1) are WRONG for GFX1013
                // (wave64). Like compile_mul_mm, we MUST set internally
                // consistent values or the shader's subgroup reductions are
                // mis-sized and the output is garbage/zero. See compile_flash.
                ShaderClass::Flash => cache.compile_flash(name, spv),
                ShaderClass::Plain => cache.compile_one(name, spv),
            };
            if let Err(e) = result {
                failed.push(format!("{name}: {e}"));
            }
        }
        if !failed.is_empty() {
            return Err(format!(
                "PipelineCache: {} shader(s) failed to compile:\n  {}",
                failed.len(),
                failed.join("\n  ")
            ));
        }

        // BN=8 narrow-tile GEMM variant for forward_batched's T<=8 decode
        // batches, compiled from the same SPIR-V as the BN=64 mul_mm pipeline
        // above. Not optional: forward_batched hard-depends on it, so a
        // missing/failed compile must fail loudly here rather than silently
        // falling back to the padded BN=64 path at dispatch time.
        const NARROW_SRC: &str = "matmul_f16_f32_fp32";
        match shader_spvs.get(NARROW_SRC) {
            Some(&spv) => cache
                .compile_mul_mm_narrow(NARROW_SRC, spv)
                .map_err(|e| format!("PipelineCache: {NARROW_SRC}_bn8 failed to compile: {e}"))?,
            None => {
                return Err(format!(
                    "PipelineCache: source shader '{NARROW_SRC}' not found in shader_spvs; \
                     cannot compile {NARROW_SRC}_bn8"
                ));
            }
        }

        // GEMM campaign Phase 1: geometry siblings of the swept
        // matmul_f16_f32_f16_aligned winner (push_constants::GEMM_GEOM_COMBOS
        // / gemm_pick), compiled from the Phase 0 SPIR-V registered in
        // scripts/compile_shaders.sh. `gemm_variant_k` names one of these
        // siblings whenever a dispatch shape is in the swept win region AND
        // VLLM_VULKAN_GEMM_F16ALIGNED != "0" (default ON), so — like the
        // _bn8/_cols siblings above — a missing/failed compile must fail
        // loudly here rather than surface as a missing-pipeline panic at
        // first dispatch. The SPIR-V itself is optional in the shader set
        // (Mac cross-builds always include it, but skip gracefully if a
        // trimmed shader_spvs is ever passed in, matching MulMm's own
        // per-shader compile loop above rather than the _bn8/_cols hard
        // requirement).
        const GEMM_GEOM_SRC: &str = "matmul_f16_f32_f16_aligned";
        if let Some(&spv) = shader_spvs.get(GEMM_GEOM_SRC) {
            cache.compile_mul_mm_geom(GEMM_GEOM_SRC, spv, crate::push_constants::GEMM_GEOM_COMBOS)
                .map_err(|e| format!("PipelineCache: {GEMM_GEOM_SRC} geom siblings: {e}"))?;
        }

        // Phase A quant-batched-GEMM: geometry siblings of the mlx4/q8_0 mul_mm
        // SPIR-V, reusing the SAME swept dense tile shapes as the f16 sibling
        // sweep (`GEMM_GEOM_COMBOS`/`gemm_pick`) — the tile geometry is
        // orthogonal to A's storage format (see `compile_mul_mm_quant_geom`'s
        // doc-comment). `gemm_variant_quant_k` names one of these siblings
        // whenever VLLM_VULKAN_GEMM_QUANT=1 selects the quant GEMM path for a
        // dispatch shape in the swept win region. Optional in the shader set
        // (skip gracefully if a trimmed shader_spvs is passed, mirroring the
        // f16 GEMM_GEOM_SRC block above) — a real cross-build always includes
        // both.
        for quant_src in ["matmul_mlx4_f32_fp32", "matmul_q8_0_f32_fp32", "matmul_mlx4_id_f32_fp32",
                          "matmul_mlx4_id_gateup_silu_f32_fp32"] {
            if let Some(&spv) = shader_spvs.get(quant_src) {
                cache.compile_mul_mm_quant_geom(quant_src, spv, crate::push_constants::GEMM_GEOM_COMBOS)
                    .map_err(|e| format!("PipelineCache: {quant_src} geom siblings: {e}"))?;
            }
        }

        // Phase 2 sparse-BN (plan-epilogue-fused-moe-gemm.md §3): BN=16/32
        // siblings of the MUL_MAT_ID grouped-expert quant GEMMs specifically
        // (not the dense mlx4/q8_0 bases above — those have no per-expert
        // token-count skew to exploit). Selected at dispatch time by
        // `gemm_variant_quant_id_bn` keyed on tokens/expert, independent of
        // the (k,n)-shape-keyed `gemm_variant_quant_k` sibling picked above.
        for id_src in ["matmul_mlx4_id_f32_fp32", "matmul_mlx4_id_gateup_silu_f32_fp32"] {
            if let Some(&spv) = shader_spvs.get(id_src) {
                cache.compile_mul_mm_quant_id_bn(id_src, spv)
                    .map_err(|e| format!("PipelineCache: {id_src} sparse-BN siblings: {e}"))?;
            }
        }

        // Batched multi-column matvec variants for forward_batched (T=1..8).
        // rows=max(1,8/t) — see matvec_cols_variant. Like _bn8, forward_batched
        // hard-depends on the f16 base, so its compile failures must surface here.
        const MV_COLS_RC: [(u32, u32); 7] =
            [(4, 2), (2, 3), (2, 4), (1, 5), (1, 6), (1, 7), (1, 8)];
        const MV_COLS_SRC: &str = "mul_mat_vec_f16_f32_f32";
        match shader_spvs.get(MV_COLS_SRC) {
            Some(&spv) => {
                for (rows, cols) in MV_COLS_RC {
                    cache.compile_matvec_cols(MV_COLS_SRC, spv, rows, cols)
                        .map_err(|e| format!("PipelineCache: {MV_COLS_SRC} cols variant: {e}"))?;
                }
            }
            None => {
                return Err(format!(
                    "PipelineCache: source shader '{MV_COLS_SRC}' not found in shader_spvs; \
                     cannot compile _r*_c* cols variants"
                ));
            }
        }

        // Design C — column-batched DEQUANT matvec cols variants. Same SPIR-V as
        // the per-token q8_0/q4 decode kernels (mul_mat_vec.comp, NUM_COLS spec
        // constant), so each workgroup streams+dequantizes its weight rows ONCE
        // and MACs across all T token-columns — the batched-verify flip for
        // quantized-resident models (matvec_cols_variant picks these bases for a
        // q8_0/q4 weight at t>1). Best-effort: a build that did not compile a
        // given codec's base still runs the f16 verify; only the codecs actually
        // resident need their cols siblings. When present, a compile failure is
        // still fatal (a silently-missing pipeline would fault at dispatch).
        for quant_src in [
            "mul_mat_vec_q8_0deq_f32_f32",
            "mul_mat_vec_q4_0deq_f32_f32",
            "mul_mat_vec_q4_kdeq_f32_f32",
        ] {
            if let Some(&spv) = shader_spvs.get(quant_src) {
                for (rows, cols) in MV_COLS_RC {
                    cache.compile_matvec_cols(quant_src, spv, rows, cols)
                        .map_err(|e| format!("PipelineCache: {quant_src} cols variant: {e}"))?;
                }
            }
        }

        // Design-A batched-verify (MTP re-gate, spec §6): the GENUINE
        // single-stream `mul_mat_vec_{f16,q8_0}_cols` siblings (d76538d) — the
        // weight is read ONCE and reused across all T columns, unlike MV_COLS_SRC
        // above (base.glsl `_r*_c*`, which re-streams the weight per column → no
        // amortization → the 0.951× Design-B failure reborn). `qwen35_matvec_cols`
        // names `{base}_r{rows}_c{t}` for the GDN in/out_proj + attn q/k/v/o VERIFY
        // projections (T=DEPTH+1 ≤ 8, rows=max(1,8/t) mirroring MV_COLS_SRC).
        // Hard-compiled here so a first-cycle verify never stalls on pipeline
        // creation; OPTIONAL in the shader set (skip gracefully if a trimmed
        // shader_spvs omits them, mirroring the GEMM_GEOM blocks below — the
        // dispatch path falls back to `qwen35_gemm` when a variant is absent).
        // `mul_mat_vec_mlx4_cols` (cbc5843): the fleet's REAL 4-bit affine
        // format — the DEQUANT-cols twin of `mul_mat_vec_q8_0_cols` (unpack +
        // affine-dequantize each nibble ONCE, reuse the scalar across all T
        // token columns). Registered here so the qwen3.6 batched prefill /
        // spec-verify projections (`qwen35_matvec_cols`, Mlx4 branch) find the
        // `_r*_c*` variant without an on-demand compile stall; OPTIONAL in the
        // shader set (skip if a trimmed `shader_spvs` omits it — the dispatch
        // falls back to the serial `qwen35_matvec` per-token path).
        for cols_base in ["mul_mat_vec_f16_cols", "mul_mat_vec_q8_0_cols", "mul_mat_vec_mlx4_cols"] {
            if let Some(&spv) = shader_spvs.get(cols_base) {
                for (rows, cols) in [(4u32, 2u32), (2, 3), (2, 4), (1, 5), (1, 6), (1, 7), (1, 8)] {
                    cache.compile_matvec_cols(cols_base, spv, rows, cols)
                        .map_err(|e| format!("PipelineCache: {cols_base} cols variant: {e}"))?;
                }
            }
        }

        log::info!(
            "PipelineCache: {} pipelines compiled.",
            cache.pipelines.len()
        );

        Ok(cache)
    }

    fn compile_one(&mut self, name: &str, spv: &[u8]) -> Result<(), String> {
        self.compile_one_with_spec(name, spv, &[])
    }

    // pub(crate) rather than private: exploratory tests (see
    // src/lib.rs's matvec-related test modules) need to compile
    // additional specialization-constant combinations beyond the fixed
    // set compile_matvec hardcodes, to measure whether a given BLOCK_SIZE/
    // NUM_ROWS combination is worth adding as a real, permanent variant
    // before committing to it.
    pub(crate) fn compile_one_with_spec(
        &mut self,
        name: &str,
        spv: &[u8],
        spec_constants: &[(u32, u32)], // (constantID, value) pairs
    ) -> Result<(), String> {
        // Validate SPIR-V alignment.
        if spv.len() % 4 != 0 {
            return Err(format!("SPIR-V for '{name}' has unaligned size {}", spv.len()));
        }
        // Re-interpret as &[u32].
        let code: &[u32] = unsafe {
            std::slice::from_raw_parts(spv.as_ptr() as *const u32, spv.len() / 4)
        };

        let module_ci = vk::ShaderModuleCreateInfo::default().code(code);
        let module = unsafe { self.device.create_shader_module(&module_ci, None) }
            .map_err(|e| format!("create_shader_module for '{name}': {e}"))?;

        // Push constant range: up to 128 bytes (Vulkan guaranteed minimum).
        let pc_range = vk::PushConstantRange::default()
            .stage_flags(vk::ShaderStageFlags::COMPUTE)
            .offset(0)
            .size(128);

        let layout_ci = vk::PipelineLayoutCreateInfo::default()
            .set_layouts(std::slice::from_ref(&self.descriptor_set_layout))
            .push_constant_ranges(std::slice::from_ref(&pc_range));
        let layout = unsafe { self.device.create_pipeline_layout(&layout_ci, None) }
            .map_err(|e| format!("create_pipeline_layout for '{name}': {e}"))?;

        let entry = c"main";

        // Build specialization constant info if provided.
        // Each entry: {constantID, offset into data, size=4}
        // Data: tightly packed u32 values.
        // All allocations must outlive the vkCreateComputePipelines call.
        let spec_data: Vec<u32> = spec_constants.iter().map(|(_, v)| *v).collect();
        let spec_entries: Vec<vk::SpecializationMapEntry> = spec_constants
            .iter()
            .enumerate()
            .map(|(i, (id, _))| vk::SpecializationMapEntry {
                constant_id: *id,
                offset: (i * 4) as u32,
                size: 4,
            })
            .collect();

        let pipelines = if spec_constants.is_empty() {
            let stage = vk::PipelineShaderStageCreateInfo::default()
                .stage(vk::ShaderStageFlags::COMPUTE)
                .module(module)
                .name(entry);
            let pipeline_ci = vk::ComputePipelineCreateInfo::default()
                .stage(stage)
                .layout(layout);
            unsafe {
                self.device.create_compute_pipelines(
                    vk::PipelineCache::null(),
                    std::slice::from_ref(&pipeline_ci),
                    None,
                )
            }
            .map_err(|(_, e)| format!("create_compute_pipelines for '{name}': {e}"))?
        } else {
            // spec_info borrows spec_entries and spec_data which are on this stack frame.
            let spec_info = vk::SpecializationInfo::default()
                .map_entries(&spec_entries)
                .data(bytemuck::cast_slice(&spec_data));
            let stage = vk::PipelineShaderStageCreateInfo::default()
                .stage(vk::ShaderStageFlags::COMPUTE)
                .module(module)
                .name(entry)
                .specialization_info(&spec_info);
            let pipeline_ci = vk::ComputePipelineCreateInfo::default()
                .stage(stage)
                .layout(layout);
            unsafe {
                self.device.create_compute_pipelines(
                    vk::PipelineCache::null(),
                    std::slice::from_ref(&pipeline_ci),
                    None,
                )
            }
            .map_err(|(_, e)| format!("create_compute_pipelines for '{name}': {e}"))?
        };

        self.pipelines.insert(
            name.to_owned(),
            Pipeline {
                name: name.to_owned(),
                module,
                layout,
                pipeline: pipelines[0],
                binding_count: MAX_BINDINGS,
            },
        );
        Ok(())
    }

    /// Compile a shader with the standard matvec specialization constants.
    /// Base (NUM_ROWS=1) variant: BLOCK_SIZE=128, NUM_COLS=1 (see the inline
    /// `(0, 128)` note below for why 128 over 512). Also compiles NUM_ROWS=2,
    /// NUM_ROWS=4, and NUM_ROWS=8 (`_r2`/`_r4`/`_r8`) variants for wider
    /// matrices. (Upstream had dropped `_r2` as dead weight; the fork keeps it
    /// because the batch-dispatch geometry work re-introduced dispatch sites
    /// for it — so upstream's `r2_matvec_variant_is_no_longer_compiled`
    /// regression guard does NOT apply to the fork.)
    pub fn compile_matvec(&mut self, name: &str, spv: &[u8]) -> Result<(), String> {
        self.compile_one_with_spec(name, spv, &[
            (0, 128), // BLOCK_SIZE = 128 (not 512, see below)
            (1, 1),   // NUM_ROWS = 1
            (2, 1),   // NUM_COLS = 1
        ])?;
        // NUM_ROWS=2/4/8 variants for wider matrices. These are expected to
        // succeed on supported hardware (only _r16/_r32 hang pipeline creation
        // on GFX1013 and are deliberately not attempted) — surface failures
        // instead of silently dropping them.
        for (suffix, rows) in [("_r2", 2u32), ("_r4", 4), ("_r8", 8)] {
            let variant = format!("{name}{suffix}");
            self.compile_one_with_spec(&variant, spv, &[(0, 512), (1, rows), (2, 1)])
                .map_err(|e| format!("{variant}: {e}"))?;
        }
        Ok(())
    }

    /// Batched multi-column matvec `<name>_r{rows}_c{cols}` from the same SPIR-V as
    /// compile_matvec. Each workgroup streams its `rows` weight rows ONCE and reuses
    /// them across `cols` token-columns (forward_batched T<=8 verify). rows*cols<=8
    /// keeps tmpsh LDS (cols*rows*512*4 <= 16KB) and accumulator registers (<=8) at
    /// the proven-safe _r8 budget (higher products hit the _r16 GFX1013 hang / LDS OOM).
    pub fn compile_matvec_cols(&mut self, name: &str, spv: &[u8], rows: u32, cols: u32) -> Result<(), String> {
        debug_assert!(rows * cols <= 8);
        // BLOCK_SIZE was hardcoded to 512 — measured as the WORST choice for every
        // cols>1 config (cluster A/B 2026-07-20, 12 paired interleaved reps @1850,
        // rel-sd <0.8%): it leaves 1.39-1.52x on the table at T=4/8 on the **f16**
        // cols path `forward_batched` already uses in production today. The winners
        // below are the measured best over bs in {512,256,128,64} x rows in {8,4,2,1};
        // the caller's rows (8/cols) already equals each winner's rows, so only
        // BLOCK_SIZE needed fixing — and the variant name doesn't encode bs, so this
        // is transparent to every call site. Optimum is dtype-dependent: f16 wants a
        // wider block at T=2/4, the quant (dequant-in-loop) kernels want bs=64.
        // LDS (tmpsh = cols*rows*bs*4 <= 16 KB) holds for every row below.
        let bs = cols_block_size(name, cols);
        debug_assert!(cols * rows * bs * 4 <= 16384);
        let variant = format!("{name}_r{rows}_c{cols}");
        self.compile_one_with_spec(&variant, spv, &[(0, bs), (1, rows), (2, cols)])
            .map_err(|e| format!("{variant}: {e}"))
    }

    /// Compile the small-BLOCK_SIZE geometry siblings `<name>_bs{bs}_r{rows}`
    /// for the small-k MoE/deltanet dispatches. `combos` come from the on-node
    /// debug_*_geometry sweep (push_constants::geom_combos_for) and were each
    /// creation-vetted on GFX1013 there, so plain (non-watchdog) creation is
    /// safe at startup. LDS = rows*bs*4 <= 16 KB; rows <= 8 (`_r16` hangs
    /// GFX1013 pipeline creation).
    pub fn compile_matvec_geom(
        &mut self,
        name: &str,
        spv: &[u8],
        combos: &[(u32, u32)],
    ) -> Result<(), String> {
        for &(bs, rows) in combos {
            debug_assert!(
                rows * bs * 4 <= 16384 && matches!(rows, 1 | 2 | 4 | 8) && bs.is_power_of_two(),
                "geometry combo bs={bs} rows={rows} violates the GFX1013-safe envelope"
            );
            let variant = format!("{name}_bs{bs}_r{rows}");
            self.compile_one_with_spec(&variant, spv, &[(0, bs), (1, rows), (2, 1)])
                .map_err(|e| format!("{variant}: {e}"))?;
        }
        Ok(())
    }

    /// G2 watchdog compile (geometry sweep): compile `name` with `spec_constants`
    /// on a scratch thread and wait at most `timeout`. Some geometries hang
    /// `vkCreateComputePipelines` FOREVER on GFX1013/RADV (`_r16`/`_r32` proven;
    /// new BLOCK_SIZE values are unproven until swept), so the creation must be
    /// abandonable. Returns:
    ///   Ok(true)  — compiled and inserted into the cache, ready to dispatch.
    ///   Ok(false) — creation TIMED OUT; the scratch thread + its Vk objects are
    ///               deliberately leaked (the driver never returns; destroying
    ///               from another thread would race). Caller must skip the variant.
    ///   Err(_)    — ordinary compile error.
    pub fn compile_with_spec_timeout(
        &mut self,
        name: &str,
        spv: &[u8],
        spec_constants: &[(u32, u32)],
        timeout: std::time::Duration,
    ) -> Result<bool, String> {
        if spv.len() % 4 != 0 {
            return Err(format!("SPIR-V for '{name}' has unaligned size {}", spv.len()));
        }
        let device = self.device.clone();
        let dsl = self.descriptor_set_layout;
        let name_owned = name.to_owned();
        let spv_owned: Vec<u8> = spv.to_vec();
        let spec_owned: Vec<(u32, u32)> = spec_constants.to_vec();
        let (tx, rx) = std::sync::mpsc::channel();
        std::thread::spawn(move || {
            let result = (|| -> Result<(vk::ShaderModule, vk::PipelineLayout, vk::Pipeline), String> {
                let code: &[u32] = unsafe {
                    std::slice::from_raw_parts(spv_owned.as_ptr() as *const u32, spv_owned.len() / 4)
                };
                let module_ci = vk::ShaderModuleCreateInfo::default().code(code);
                let module = unsafe { device.create_shader_module(&module_ci, None) }
                    .map_err(|e| format!("create_shader_module for '{name_owned}': {e}"))?;
                let pc_range = vk::PushConstantRange::default()
                    .stage_flags(vk::ShaderStageFlags::COMPUTE)
                    .offset(0)
                    .size(128);
                let layout_ci = vk::PipelineLayoutCreateInfo::default()
                    .set_layouts(std::slice::from_ref(&dsl))
                    .push_constant_ranges(std::slice::from_ref(&pc_range));
                let layout = unsafe { device.create_pipeline_layout(&layout_ci, None) }
                    .map_err(|e| format!("create_pipeline_layout for '{name_owned}': {e}"))?;
                let spec_data: Vec<u32> = spec_owned.iter().map(|(_, v)| *v).collect();
                let spec_entries: Vec<vk::SpecializationMapEntry> = spec_owned
                    .iter()
                    .enumerate()
                    .map(|(i, (id, _))| vk::SpecializationMapEntry {
                        constant_id: *id,
                        offset: (i * 4) as u32,
                        size: 4,
                    })
                    .collect();
                let spec_info = vk::SpecializationInfo::default()
                    .map_entries(&spec_entries)
                    .data(bytemuck::cast_slice(&spec_data));
                let stage = vk::PipelineShaderStageCreateInfo::default()
                    .stage(vk::ShaderStageFlags::COMPUTE)
                    .module(module)
                    .name(c"main")
                    .specialization_info(&spec_info);
                let pipeline_ci = vk::ComputePipelineCreateInfo::default()
                    .stage(stage)
                    .layout(layout);
                let pipelines = unsafe {
                    device.create_compute_pipelines(
                        vk::PipelineCache::null(),
                        std::slice::from_ref(&pipeline_ci),
                        None,
                    )
                }
                .map_err(|(_, e)| format!("create_compute_pipelines for '{name_owned}': {e}"))?;
                Ok((module, layout, pipelines[0]))
            })();
            let _ = tx.send(result);
        });
        match rx.recv_timeout(timeout) {
            Ok(Ok((module, layout, pipeline))) => {
                self.pipelines.insert(
                    name.to_owned(),
                    Pipeline {
                        name: name.to_owned(),
                        module,
                        layout,
                        pipeline,
                        binding_count: MAX_BINDINGS,
                    },
                );
                Ok(true)
            }
            Ok(Err(e)) => Err(e),
            Err(_) => {
                log::warn!(
                    "compile_with_spec_timeout('{name}'): pipeline creation exceeded \
                     {timeout:?}; scratch thread abandoned (GFX1013-style driver hang)"
                );
                Ok(false)
            }
        }
    }

    /// Compile a `*_subgroup` matvec variant. Its reduction (mul_mat_vec_base.glsl,
    /// USE_SUBGROUP_ADD_NO_SHMEM) does a bare subgroupAdd with no cross-subgroup
    /// shared-memory fixup, so it is correct ONLY when the whole workgroup is one
    /// subgroup. Set BLOCK_SIZE = device subgroup_size; do NOT emit _r* siblings
    /// (matvec_variant_core returns rows=1 for `_subgroup`, so they are never
    /// dispatched, and _subgroup_r* would be equally mis-reduced).
    pub fn compile_matvec_subgroup(&mut self, name: &str, spv: &[u8]) -> Result<(), String> {
        self.compile_one_with_spec(name, spv, &[
            (0, self.subgroup_size), // BLOCK_SIZE = subgroup_size (one subgroup)
            (1, 1),                  // NUM_ROWS = 1
            (2, 1),                  // NUM_COLS = 1
        ])
    }

    /// Compile a tiled-GEMM (mul_mm.comp) pipeline with spec constants that are
    /// internally consistent for the scalar (non-coopmat) path.
    ///
    /// constant_id map (see mul_mm.comp):
    ///   0 BLOCK_SIZE, 1 BM, 2 BN, 3 BK (quant only), 4 WM, 5 WN,
    ///   6 WMITER, 7 TM, 8 TN, 9 TK (coopmat only), 10 WARP.
    ///
    /// The scalar path splits each BMxBN output tile across
    /// (BM/WM)*(BN/WN) logical warps of WARP invocations, so the workgroup
    /// MUST have BLOCK_SIZE = (BM/WM)*(BN/WN)*WARP threads. Likewise WNITER =
    /// (WM*WN)/(WARP*TM*TN*WMITER) must be a positive integer. For the f16/f32
    /// "small" tile (BM=BN=64, WM=WN=32, WMITER=2, TM=4, TN=2, WARP=32) that
    /// gives BLOCK_SIZE=128 and WNITER=2 — the values llama.cpp uses for this
    /// shape. The shader's own defaults (BLOCK_SIZE=64) are NOT consistent and
    /// produce all-zero output, so we never rely on them.
    pub fn compile_mul_mm(&mut self, name: &str, spv: &[u8]) -> Result<(), String> {
        const BM: u32 = 64;
        const BN: u32 = 64;
        const WM: u32 = 32;
        const WN: u32 = 32;
        const WMITER: u32 = 2;
        const TM: u32 = 4;
        const TN: u32 = 2;
        // WARP here is a SOFTWARE tile-warp width (thread partition of the BMxBN
        // tile), NOT the hardware subgroup — the scalar path issues no subgroup ops.
        // It stays 32 on every device; do not derive it from subgroup_size.
        const WARP: u32 = 32;
        let block_size = (BM / WM) * (BN / WN) * WARP; // 128
        self.compile_one_with_spec(name, spv, &[
            (0, block_size),
            (1, BM),
            (2, BN),
            (4, WM),
            (5, WN),
            (6, WMITER),
            (7, TM),
            (8, TN),
            (10, WARP),
        ])
    }

    /// Compile a quantized tiled-GEMM (mul_mm.comp, DATA_A_Q8_0/DATA_A_MLX4)
    /// pipeline — Phase A of the quant-batched-matmul campaign
    /// (plan-quant-batched-matmul.md). Identical tile geometry to
    /// `compile_mul_mm` (BM=BN=64, WM=WN=32, WMITER=2, TM=4, TN=2, WARP=32,
    /// BLOCK_SIZE=128) PLUS spec constant 3 = BK = 32, which the quant
    /// `load_a_to_shmem` heads require (`mul_mm.comp:128`: "Assumed to be 32
    /// if working with a quant" — the f32/f16 heads `#define BK 32` directly
    /// and never declare this spec constant, so `compile_mul_mm` correctly
    /// omits it; the quant heads DO declare it and default to 16, which would
    /// silently mis-tile the K-loop if left unset).
    pub fn compile_mul_mm_quant(&mut self, name: &str, spv: &[u8]) -> Result<(), String> {
        const BM: u32 = 64;
        const BN: u32 = 64;
        const WM: u32 = 32;
        const WN: u32 = 32;
        const WMITER: u32 = 2;
        const TM: u32 = 4;
        const TN: u32 = 2;
        const WARP: u32 = 32;
        const BK: u32 = 32;
        let block_size = (BM / WM) * (BN / WN) * WARP; // 128
        self.compile_one_with_spec(name, spv, &[
            (0, block_size),
            (1, BM),
            (2, BN),
            (3, BK),
            (4, WM),
            (5, WN),
            (6, WMITER),
            (7, TM),
            (8, TN),
            (10, WARP),
        ])
    }

    /// Compile GEMM-campaign Phase A geometry siblings of a QUANTIZED mul_mm
    /// SPIR-V, mirroring `compile_mul_mm_geom` but with the BK=32 spec
    /// constant the quant heads require (see `compile_mul_mm_quant`). WM=WN=32,
    /// WMITER=2 held fixed, same as the f16 sibling sweep — the swept dense
    /// tile shapes (`GEMM_GEOM_COMBOS`) are reused unchanged since the tile
    /// geometry is orthogonal to A's storage format (dequant lands in the same
    /// LDS `buf_a`, at the same footprint, regardless of quant vs f16 — the
    /// campaign plan's central amortization argument).
    pub fn compile_mul_mm_quant_geom(
        &mut self,
        name: &str,
        spv: &[u8],
        combos: &[(u32, u32, u32, u32, u32)],
    ) -> Result<(), String> {
        const WM: u32 = 32;
        const WN: u32 = 32;
        const WMITER: u32 = 2;
        const BK: u32 = 32;
        for &(bm, bn, warp, tm, tn) in combos {
            let block_size = (bm / WM) * (bn / WN) * warp;
            debug_assert!(
                block_size >= 1 && block_size <= 1024
                    && (WM * WN) % (warp * tm * tn * WMITER) == 0,
                "quant gemm geom combo bm={bm} bn={bn} warp={warp} tm={tm} tn={tn} \
                 violates BLOCK_SIZE<=1024 / integer-WNITER invariants"
            );
            let variant = format!("{name}_bm{bm}_bn{bn}_w{warp}_tm{tm}_tn{tn}");
            self.compile_one_with_spec(&variant, spv, &[
                (0, block_size),
                (1, bm),
                (2, bn),
                (3, BK),
                (4, WM),
                (5, WN),
                (6, WMITER),
                (7, tm),
                (8, tn),
                (10, warp),
            ])
            .map_err(|e| format!("{variant}: {e}"))?;
        }
        Ok(())
    }

    /// Phase 2 (plan-epilogue-fused-moe-gemm.md §3): sparse-BN siblings of a
    /// MUL_MAT_ID quant GEMM (`matmul_mlx4_id_f32_fp32` or
    /// `matmul_mlx4_id_gateup_silu_f32_fp32`), registered as `<name>_bn16`/
    /// `<name>_bn32`. The routed GEMM's N (column) dim is tokens-per-expert,
    /// which at small T (e.g. ~16 @ T=512, ~32 @ T=1024) is FAR under the
    /// dense BM=BN=64 default's BN=64 column tile — wasting up to ~75% of the
    /// N-lanes as masked padding and starving resident-workgroup count (less
    /// latency hiding on this memory-bound kernel). BM=64/BK=32/WM=32 held
    /// fixed (weight-row tiling and the quant dequant head are unaffected by
    /// the token/N dim); WN/TN shrink with BN so WNITER stays an integer:
    ///   BN=16: WN=16,TN=1 → BLOCK_SIZE=(64/32)*(16/16)*32=64,
    ///          WNITER=(32*16)/(32*4*1*2)=2
    ///   BN=32: WN=32,TN=1 → BLOCK_SIZE=(64/32)*(32/32)*32=64,
    ///          WNITER=(32*32)/(32*4*1*2)=4
    /// Both integer (asserted), so — like every other geom sibling here — a
    /// bad combo would produce all-zero output rather than a silent
    /// mis-tile, caught by `debug_moe_gemm_correctness`/
    /// `debug_moe_gemm_fused_correctness` before this is ever cluster-gated.
    pub fn compile_mul_mm_quant_id_bn(&mut self, name: &str, spv: &[u8]) -> Result<(), String> {
        const BM: u32 = 64;
        const WM: u32 = 32;
        const WMITER: u32 = 2;
        const TM: u32 = 4;
        const TN: u32 = 1;
        const WARP: u32 = 32;
        const BK: u32 = 32;
        for &bn in &[16u32, 32u32] {
            let wn = bn;
            let block_size = (BM / WM) * (bn / wn) * WARP;
            let wniter = (WM * wn) / (WARP * TM * TN * WMITER);
            debug_assert!(
                block_size >= 1 && block_size <= 1024 && wniter >= 1 && (WM * wn) % (WARP * TM * TN * WMITER) == 0,
                "quant MUL_MAT_ID sparse-BN combo bn={bn} wn={wn} violates \
                 BLOCK_SIZE<=1024 / integer-WNITER invariants"
            );
            let variant = format!("{name}_bn{bn}");
            self.compile_one_with_spec(&variant, spv, &[
                (0, block_size),
                (1, BM),
                (2, bn),
                (3, BK),
                (4, WM),
                (5, wn),
                (6, WMITER),
                (7, TM),
                (8, TN),
                (10, WARP),
            ])
            .map_err(|e| format!("{variant}: {e}"))?;
        }
        Ok(())
    }

    /// Compile a SECOND tiled-GEMM pipeline from the SAME `matmul_f16_f32_fp32`
    /// SPIR-V, registered under `<name>_bn8`, with a narrow BN=8 token tile.
    ///
    /// `forward_batched` calls mul_mm for T=1..8 tokens through the BN=64
    /// pipeline above, which pads the token (N) dimension up to 64 columns —
    /// every call does a 64-token prefill's worth of MACs regardless of the
    /// true T. This variant tiles N in chunks of 8 instead, so T<=8 decode
    /// batches only pay for ~8 columns of work (rounded up to the BN=8 tile,
    /// with store-masked padding keeping results bit-identical for T<8).
    ///
    /// Spec constants: BLOCK_SIZE=64, BM=64, BN=8, WM=32, WN=8, WMITER=2,
    /// TM=4, TN=1, WARP=32. Derivation (see compile_mul_mm doc-comment):
    ///   BLOCK_SIZE = (BM/WM)*(BN/WN)*WARP = (64/32)*(8/8)*32 = 2*1*32 = 64
    ///   WNITER = (WM*WN)/(WARP*TM*TN*WMITER) = (32*8)/(32*4*1*2) = 256/256 = 1
    /// Both are positive integers, so the tile geometry is internally
    /// consistent (a wrong combo produces all-zero output, caught by the
    /// bit-exact forward_batched tests).
    pub fn compile_mul_mm_narrow(&mut self, name: &str, spv: &[u8]) -> Result<(), String> {
        const BM: u32 = 64;
        const BN: u32 = 8;
        const WM: u32 = 32;
        const WN: u32 = 8;
        const WMITER: u32 = 2;
        const TM: u32 = 4;
        const TN: u32 = 1;
        const WARP: u32 = 32;
        let block_size = (BM / WM) * (BN / WN) * WARP; // 64
        let variant = format!("{name}_bn8");
        self.compile_one_with_spec(&variant, spv, &[
            (0, block_size),
            (1, BM),
            (2, BN),
            (4, WM),
            (5, WN),
            (6, WMITER),
            (7, TM),
            (8, TN),
            (10, WARP),
        ])
        .map_err(|e| format!("{variant}: {e}"))
    }

    /// Compile GEMM-campaign Phase 1 geometry siblings of a mul_mm SPIR-V (the
    /// swept winner tile shapes) as
    /// `<name>_bm{BM}_bn{BN}_w{WARP}_tm{TM}_tn{TN}` — mirrors
    /// `compile_matvec_geom`'s `_bs{bs}_r{rows}` sibling convention. WM=WN=32,
    /// WMITER=2 are held fixed (the `debug_gemm_geometry` sweep tool's own
    /// fixed axes; see `push_constants::GEMM_GEOM_COMBOS` / `gemm_pick`).
    /// Each combo's BLOCK_SIZE=(BM/WM)*(BN/WN)*WARP and
    /// WNITER=(WM*WN)/(WARP*TM*TN*WMITER) must be internally consistent (see
    /// `compile_mul_mm`'s doc-comment) — asserted here; a bad combo would
    /// otherwise silently compile a pipeline that produces all-zero output.
    pub fn compile_mul_mm_geom(
        &mut self,
        name: &str,
        spv: &[u8],
        combos: &[(u32, u32, u32, u32, u32)],
    ) -> Result<(), String> {
        const WM: u32 = 32;
        const WN: u32 = 32;
        const WMITER: u32 = 2;
        for &(bm, bn, warp, tm, tn) in combos {
            let block_size = (bm / WM) * (bn / WN) * warp;
            debug_assert!(
                block_size >= 1 && block_size <= 1024
                    && (WM * WN) % (warp * tm * tn * WMITER) == 0,
                "gemm geom combo bm={bm} bn={bn} warp={warp} tm={tm} tn={tn} \
                 violates BLOCK_SIZE<=1024 / integer-WNITER invariants"
            );
            let variant = format!("{name}_bm{bm}_bn{bn}_w{warp}_tm{tm}_tn{tn}");
            self.compile_one_with_spec(&variant, spv, &[
                (0, block_size),
                (1, bm),
                (2, bn),
                (4, WM),
                (5, WN),
                (6, WMITER),
                (7, tm),
                (8, tn),
                (10, warp),
            ])
            .map_err(|e| format!("{variant}: {e}"))?;
        }
        Ok(())
    }

    /// Compile a flash-attention (flash_attn.comp) pipeline with spec constants
    /// internally consistent for the scalar wave64 (GFX1013) path, head_dim=128.
    ///
    /// constant_id map (flash_attn_base.glsl):
    ///   0 WorkGroupSize, 1 Br, 2 Bc, 3 HSK, 4 HSV, 5 Clamp, 6 D_split,
    ///   7 row_split, 8 SubGroupSize, 9 SHMEM_STAGING, 10 Flags,
    ///   11 LIMIT_OCCUPANCY_SHMEM.
    ///
    /// Br/Bc/D_split must satisfy:
    ///   cols_per_iter  = WorkGroupSize / D_split / row_split
    ///   cols_per_thread = Bc / cols_per_iter            (must be a positive int)
    ///   HSK_per_thread = HSK / D_split                  (>=4, multiple of 4)
    ///   num_subgroups  = WorkGroupSize / SubGroupSize
    /// For HSK=HSV=128: WorkGroupSize=128, D_split=16 → HSK_per_thread=8,
    /// cols_per_iter=8, Bc=32 → cols_per_thread=4. Br=8 (8 query rows/tile).
    /// SubGroupSize=64 (wave64). Clamp(5) and Flags(10) are set per-dispatch
    /// flavor below: a no-mask Clamp variant (decode/all-visible) and a masked
    /// Clamp variant (causal prefill). SHMEM_STAGING=0 keeps LDS tiny.
    pub fn compile_flash(&mut self, name: &str, spv: &[u8]) -> Result<(), String> {
        const WG: u32 = 128;
        const ROW_SPLIT: u32 = 1;
        // M10: derive from the device. The flash reduction's contract is
        // num_subgroups = WG/SubGroupSize (WG=128), integral for 32 and 64.
        // GFX1013 (the validated target) reports 64 → identical to the previous
        // hard-coded value, so no regression; other wave sizes get a
        // self-consistent (if not yet cluster-validated) config instead of a
        // guaranteed-wrong 64.
        let subgroup = self.subgroup_size;
        // Select head_dim (HSK=HSV), tile geometry, and D_split from the name:
        //   default  -> head_dim 128  (qwen),  D_split=16
        //   *_hs256  -> head_dim 256  (gemma sliding layers), D_split=16
        //   *_hs512  -> head_dim 512  (gemma global layers),  D_split=32
        //
        // Geometry invariants (see flash_attn.comp): cols_per_iter =
        // WG/D_split/row_split must divide Bc; HSK_per_thread = HSK/D_split must
        // be >=4 and a multiple of 4.
        //   hs128: D_split=16 -> cols_per_iter=8,  HSK_per_thread=8  (HSK_pt/4=2)
        //   hs256: D_split=16 -> cols_per_iter=8,  HSK_per_thread=16 (HSK_pt/4=4)
        //   hs512: D_split=32 -> cols_per_iter=4,  HSK_per_thread=16 (HSK_pt/4=4)
        // D_split=32 for hs512 is DELIBERATE: with D_split=16 the head_dim-512
        // path would have HSK_pt/4=8 (>4), which selects the shader's Q-register-
        // caching QK branch AND doubles per-thread Of/Sf registers (Of[8][8]) —
        // that path produces garbage on GFX1013 (cos~0). D_split=32 keeps
        // HSK_pt/4=4 so it uses the SAME simple QK path that the validated 128/256
        // variants use, and halves the per-thread accumulator footprint
        // (Of[8][4]). D_split=32 < SubGroupSize=64 so the cross-D_split shuffle
        // reductions are still a single subgroup.
        // LDS (SHMEM_STAGING=0, KV NOT staged): Qf[Br*(HSK/4+1)] vec4 dominates.
        //   hs512,Br=8 -> 8*129*16 = 16512 B; + mask/tmpsh/tmpshv4 ≈ 18 KB << 64 KB.
        let (hs, br, bc, d_split): (u32, u32, u32, u32) = if name.contains("_hs512") {
            (512, 8, 32, 32)
        } else if name.contains("_hs256") {
            (256, 8, 32, 16)
        } else {
            (128, 8, 32, 16)
        };
        // Base: Clamp=1 (KV bounds checked), no mask (Flags=0). Attends all keys.
        self.compile_one_with_spec(name, spv, &[
            (0, WG), (1, br), (2, bc), (3, hs), (4, hs),
            (5, 1),           // Clamp = 1 (bounds check KV)
            (6, d_split), (7, ROW_SPLIT), (8, subgroup),
            (9, 0),           // SHMEM_STAGING = 0
            (10, 0),          // Flags = 0 (no mask)
            (11, 0),          // LIMIT_OCCUPANCY_SHMEM = 0
        ])?;
        // Masked variant (Flags=2 -> MASK_ENABLE) for causal prefill.
        let masked = format!("{name}_mask");
        self.compile_one_with_spec(&masked, spv, &[
            (0, WG), (1, br), (2, bc), (3, hs), (4, hs),
            (5, 1),
            (6, d_split), (7, ROW_SPLIT), (8, subgroup),
            (9, 0),
            (10, 2),          // Flags = 2 (MASK_ENABLE)
            (11, 0),
        ])
        .map_err(|e| format!("{masked}: {e}"))
    }

    /// Compile rms_norm variants: plain (do_multiply=false) and weight-multiplying
    /// (do_multiply=true).  The weight-multiplying variant is registered as
    /// "<name>_mul".
    pub fn compile_rms_norm(&mut self, name: &str, spv: &[u8]) -> Result<(), String> {
        // Plain variant (do_multiply = false, the default)
        self.compile_one_with_spec(name, spv, &[])?;
        // Weight-multiplying variant (do_multiply = true, constant_id = 1)
        let mul_name = format!("{name}_mul");
        self.compile_one_with_spec(&mul_name, spv, &[
            (1, 1), // do_multiply = true
        ])
    }

    pub fn get(&self, name: &str) -> Option<&Pipeline> {
        self.pipelines.get(name)
    }

    pub fn pipeline_names(&self) -> Vec<String> {
        self.pipelines.keys().cloned().collect()
    }
}

impl Drop for PipelineCache {
    fn drop(&mut self) {
        unsafe {
            for p in self.pipelines.values() {
                self.device.destroy_pipeline(p.pipeline, None);
                self.device.destroy_pipeline_layout(p.layout, None);
                self.device.destroy_shader_module(p.module, None);
            }
            self.device.destroy_descriptor_set_layout(self.descriptor_set_layout, None);
        }
    }
}

/// Measured-best `BLOCK_SIZE` for the batched multi-column matvec
/// (`<name>_r{rows}_c{cols}`, see `PipelineCache::compile_matvec_cols`).
///
/// BLOCK_SIZE used to be hardcoded to 512, which two independent cluster A/Bs
/// measured as the WORST choice for every cols>1 config — up to **+92%** off
/// the best (qwen-27B TP-4, 2026-07-20, 12 paired reps @1850; gemma-31B TP-4,
/// 2026-07-20, 3-rep median, cos=1.0). The right value trends small, and the
/// two models AGREE on the direction and on cols=8 (→64) but not on the exact
/// cols=4 winner (qwen: 256; gemma: 64-128 depending on shape).
///
/// NOTE ON "shape-awareness": this pipeline is compiled ONCE per (rows,cols)
/// and reused for every `n` (n is a runtime push-constant, not a spec constant),
/// so BLOCK_SIZE cannot literally depend on n here without compiling bs-sibling
/// pipelines + picking at dispatch (the `compile_matvec_geom`/`geom_pick`
/// pattern the single-column path uses). That machinery is NOT justified for
/// cols=4, which measured as a FLAT region: across the qwen+gemma shapes bs128
/// is best or within ~4%, while bs256 costs up to +10% and bs64 up to +34%
/// (gemma attn.o). So cols=4 takes the robust cross-shape constant bs128 rather
/// than an n-formula overfit to a ±4% band. If a future model shows >~15% cols=4
/// sensitivity, promote this to bs-siblings + a dispatch-time shape pick.
///
/// The quant (dequant-in-loop) kernels want bs=64 throughout. The caller's rows
/// (8/cols) already equals each winner's rows, so only BLOCK_SIZE was wrong.
/// Untested cols fall back to the legacy 512 (known-safe).
///
/// Invariant the caller asserts: tmpsh LDS = `cols*rows*bs*4 <= 16 KB`.
pub(crate) fn cols_block_size(name: &str, cols: u32) -> u32 {
    let f16 = name.contains("f16");
    match (f16, cols) {
        (true, 2) => 256,  // flat vs bs512 (~+5-14%); 256 mid of the band
        (true, 4) => 128,  // robust across qwen(256-opt)/gemma(64-128-opt); flat region
        (true, 8) => 64,   // both models agree: +50-92% at bs512
        (false, 2) | (false, 4) | (false, 8) => 64, // q8_0/quant winners
        _ => 512,
    }
}

#[cfg(test)]
mod tests {
    use super::cols_block_size;

    // rows the caller passes for a given cols (rows*cols <= 8 envelope).
    fn rows_for(cols: u32) -> u32 {
        (8 / cols).max(1)
    }

    #[test]
    fn cols_block_size_matches_measured_winners() {
        // f16 (the path forward_batched uses in production today)
        assert_eq!(cols_block_size("mul_mat_vec_f16_f32_f32", 2), 256);
        assert_eq!(cols_block_size("mul_mat_vec_f16_f32_f32", 4), 128);
        assert_eq!(cols_block_size("mul_mat_vec_f16_f32_f32", 8), 64);
        // quant kernels (dequant in the inner loop) want the narrow block
        for c in [2u32, 4, 8] {
            assert_eq!(cols_block_size("mul_mat_vec_q8_0deq_f32_f32", c), 64);
        }
    }

    #[test]
    fn untested_cols_fall_back_to_legacy_512() {
        for c in [1u32, 3, 5, 6, 7] {
            assert_eq!(cols_block_size("mul_mat_vec_f16_f32_f32", c), 512);
            assert_eq!(cols_block_size("mul_mat_vec_q8_0deq_f32_f32", c), 512);
        }
    }

    /// A bad BLOCK_SIZE here is a GPU hang / LDS OOM, not just a perf bug.
    #[test]
    fn every_pick_respects_the_16kb_lds_bound() {
        for name in ["mul_mat_vec_f16_f32_f32", "mul_mat_vec_q8_0deq_f32_f32"] {
            for cols in 1u32..=8 {
                let rows = rows_for(cols);
                if rows * cols > 8 {
                    continue; // outside the compile_matvec_cols envelope
                }
                let bs = cols_block_size(name, cols);
                assert!(cols * rows * bs * 4 <= 16384,
                        "{name} cols={cols} rows={rows} bs={bs} exceeds 16KB LDS");
                assert!(bs.is_power_of_two() && (64..=512).contains(&bs));
            }
        }
    }
}
